// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkyBV18VeB6IbPK7sBbFCHXzvNcU_Lngs',
    appId: '1:476042622936:web:cad6929c0d08c8176e64ad',
    messagingSenderId: '476042622936',
    projectId: 'eksadoapp',
    authDomain: 'eksadoapp.firebaseapp.com',
    storageBucket: 'eksadoapp.appspot.com',
    measurementId: 'G-9DDRCKK1RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUjjjtEKJCQrXre6j0CgmufYj9LFKKnic',
    appId: '1:476042622936:android:afbd125570ea89496e64ad',
    messagingSenderId: '476042622936',
    projectId: 'eksadoapp',
    storageBucket: 'eksadoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23rxEckXfBHecF-4EfCCua_VdyPprPkc',
    appId: '1:476042622936:ios:8d95ce8b1a994f636e64ad',
    messagingSenderId: '476042622936',
    projectId: 'eksadoapp',
    storageBucket: 'eksadoapp.appspot.com',
    iosBundleId: 'com.example.eksadoMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB23rxEckXfBHecF-4EfCCua_VdyPprPkc',
    appId: '1:476042622936:ios:6ec54144c369d84f6e64ad',
    messagingSenderId: '476042622936',
    projectId: 'eksadoapp',
    storageBucket: 'eksadoapp.appspot.com',
    iosBundleId: 'com.example.eksadoMain.RunnerTests',
  );
}
